### ISSUE TITLE
Privilege escalation

### ISSUE THREAD

**Issue by lifeofguenter** [ginsys/ansible-role-nullmailer#2]
Currently there is no privilege escalation in place - which does not cause any warnings but corrupts the files.

**Comment by srgvg** [comment]
What do you exactly mean by "corrupting the files"?

**Comment by srgvg** [comment]
This role does not make any assumptions on become and or user usage, except every task does need to be run as root. DIfferent people might have different use cases. Some connect directly as root, and do not need any additional setting. Some connect as an unprivileged user, and need to become root. In the case of this role, this can be set on the play level.

The alternative is to have every task in every role always be explicit on setting a `become_user`, which might already be the same user as the connecting user. This to avoid any assumptions, and be explicit.

**Comment by srgvg** [comment]
going to close this issue here, further follow up in your PR #3
